// Create Constants here
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

export const ALL_CATEGORIES_CLEAR_ERRORS = "ALL_CATEGORIES_CLEAR_ERRORS";

// Products Under Category

// Create Constants here
export const ALL_CATEGORIES_PRODUCT_REQUEST = "ALL_CATEGORIES_PRODUCT_REQUEST";
export const ALL_CATEGORIES_PRODUCT_SUCCESS = "ALL_CATEGORIES_PRODUCT_SUCCESS";
export const ALL_CATEGORIES_PRODUCT_FAIL = "ALL_CATEGORIES_PRODUCT_FAIL";

export const ALL_CATEGORIES_PRODUCT_CLEAR_ERRORS =
  "ALL_CATEGORIES_PRODUCT_CLEAR_ERRORS";
